### ISSUE TITLE
[Refactoring] - styles SCSS

### ISSUE THREAD

**Issue by atpradical** [atpradical/flash-cards-team#158]
Проверить ВСЕ  файлы стилей в copmponents и pages на предмет дублирования.
Если находятся одинаковые стили, вынести их в src/styles/_common.scss.
Стараться группировать по смыслу/стилю, а не отношению к компоненте.

**Comment by EleonoraPavlova** [comment]
да, например: 


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/84507e12-1241-4a20-b2e5-a332f25e7e8e)

дублирование по таким файлам: 


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/22845f58-39df-4c08-95eb-730ba6530ac3)

**Comment by EleonoraPavlova** [comment]
много флексов везде

**Comment by EleonoraPavlova** [comment]
повторяющиеся стили так же


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/7d98ed0b-6991-43fc-82ef-4f7d3c4c2de9)



![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/0caea78b-afa4-4c42-a41c-fdd83426f712)

**Comment by EleonoraPavlova** [comment]
margin: 12px 0 12px; мона сократить   margin: 12px 0;


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/a5dda577-6af9-48bd-a948-6215fda83991)

**Comment by EleonoraPavlova** [comment]
повторки


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/05c69455-d8db-4243-b5f8-9332c88bc3f6)



![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/716979c3-7178-4b49-8975-925c2ceb328c)
