### ISSUE TITLE
[Refactor] - pages

### ISSUE THREAD

**Issue by atpradical** [atpradical/flash-cards-team#160]
1. При ховер на ссылку Forgot Password должна подсвечиваться цветом, так же как стили на Sing Up
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/b318da0e-a9a8-4502-9b98-3ecb7b864cb7)

**Comment by EleonoraPavlova** [comment]
в Sign Up тоже не подсвечивается ссылка фиолетвым


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/4fa8cbb5-9274-4666-af6b-571e69fea3e4)

**Comment by EleonoraPavlova** [comment]
тоже самое в Forgot your password


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/2c9a5af3-7f97-45d7-8898-9b441aec509e)

**Comment by EleonoraPavlova** [comment]
CardPage, при скроле LearnCard окна, картинка из него накладывается на header
нужно добавить скрол в саму компоненту



![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/660c564f-9bf4-4107-be93-6a76bd641864)

**Comment by EleonoraPavlova** [comment]
deck-list
нужно добавить стиль к cover  -  object-fit: cover, чтобы картинка не искажалась из за размеров контейнера


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/1ddd404c-6a66-4c6c-91d5-a2ffe2abea48)

**Comment by EleonoraPavlova** [comment]
в макете нет слова Actions, и бокс с action расположен с правой части, сразу перед боковым падингом
расстояние до края таблице намного более, чем на макете

![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/a17d8de0-9942-430f-9725-fb543df4d115)

**Comment by EleonoraPavlova** [comment]
немного не соответствие макету страница /deck
я не пойму почему название кнопки другое
и кнопка learn лишняя, не по макету

![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/de9e55d4-1ccb-4afb-ab20-18496de32bfa)


макет


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/cd3907d6-74f3-42d0-abe1-74277b8c50fc)

**Comment by EleonoraPavlova** [comment]
personal-info.module - использовать переменную из common


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/78e9f996-4f47-4ca6-93f7-026f1b87d68d)

**Comment by EleonoraPavlova** [comment]
не хватает ховеров в deck page


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/85101dc5-d7ef-440d-9e4e-615b09be4757)
