### ISSUE TITLE
[Refactor] - Typography component

### ISSUE THREAD

**Issue by atpradical** [atpradical/flash-cards-team#66]
Таск на рефакторинг ui-компоненты Typography. 

1. т.к. на макете в большей степени используется шрифт/вариант = 'body 2', будет лучше поправить значение по дефолту для variant атрибута.  В рамках этой задачи нужно найти все реализованные места использования Typography (и в коде / и на макете) и исправить размер текста там где вариант не добавлялся исходя из текущего значения по умолчанию = 'caption'. А там где указывался variant = 'body 2' удалить передачу лишнего пропса. 

![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/35cca653-11be-4c2c-b52a-b6277b33d3c3)

2. Добавить переносы слов по строка, свойство для стилей:   word-break: break-all; (убедиться что в местах где Typography уже используется этот стиль не дублируется. Если дублиурется - убрать, должно просто наследоваться из Typography).

3. Переписать стили, по аналогии с другими компонентами на нормальный синтаксис, сделать нормальное обращение по названию класса
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/894465aa-d584-4cf0-8ed9-d741a6ae0565)
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/8eb8f04a-4000-4948-821f-920f2f0f1feb)

4. Тогда когда Typography используется как label - убрать марджин (убедиться что в местах где Typography уже используется этот стиль не дублируется. Если дублиурется - убрать, должно просто наследоваться из Typography).
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/b105d338-3130-4a3b-844d-98c6df95871f)

Перепроверить правильность отображения после правок по ВСЕМ вхождениям и сверить с макетом (Их не мало!).

Where-used-list:

![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/aba086cc-b34a-4197-a1cd-21a0b4dbff1c)

**Comment by EleonoraPavlova** [comment]
повторка стиля  color: var(--color-dark-100), предлагаю создать класс в типографике s.gray  и передавать как пропс
