### ISSUE TITLE
[Refactor] - TextField component

### ISSUE THREAD

**Issue by atpradical** [atpradical/flash-cards-team#67]
1. В компоненте TextField есть не используемый класс s.close: - done
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/4bdfd40d-72bc-4908-8fef-e61c2182d365)
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/022029d3-4ce8-4f1b-94ce-0b82bd366a9f)

2. Кнопку для отображения/скрытия пароля не видно для password (например в sign-in).
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/c21e3b30-8eeb-4ab9-940e-b4806879705a)

3. Исправить ошибку возникает в  Control компоненте: 
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/e7a599f1-9bfa-4555-b1d2-9c04127a78a7)

4. Заменить контейнерный div на FlexContainer (удалить лишние стили из textField.module.scss)
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/07768287-27a8-499d-948b-2faf39c60963)

5. Изменить название файла, сделать через '-', чтобы было по аналогии с остальными файлами проекта: - done
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/b84e7cfc-5301-4ea4-8117-dedf0ed0b97e)

6. Починить фокус, сейчас работает только в safari:
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/46433fc3-f824-4a15-b37e-fa081d81ed3e)

7. Добавить курсив для placeholder текста: - done
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/c415e476-3585-4962-bd6b-392499fda1cd)

8. При выборе подсказок браузера для значения - перестают работать стили (починить минимум для Chrome) - done
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/6d9217ee-4352-4155-a2e4-45273a77515a)

9. нет бордер-радуисов - done
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/5cf973dd-8c75-4e28-93aa-7d03a2a2186c)

where-used-list:
![Image](https://github.com/atpradical/flash-cards-team/assets/137553541/a4d64c33-08cf-4fa2-8898-e55f3bb3a3d0)

**Comment by EleonoraPavlova** [comment]
в sign up  тоже не видна кнопка сокрытия открытия пароля, но без синей точки


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/744669d5-d4f7-49da-bbb3-3f6aa1b90d7f)

**Comment by EleonoraPavlova** [comment]
input with type search also doesn't work, no icon x


![Image](https://github.com/atpradical/flash-cards-team/assets/82901679/4830aac2-d190-4d64-9d68-3647db7db875)
